### ISSUE TITLE
chai to be devDependencies to make it faster for users to integrate

### ISSUE THREAD

**Issue by stefek99** [WingsDao/wings-bridge#2]
```+ @wings_platform/wings-bridge@1.0.4
added 296 packages in 40.064s

"dependencies": {
    "chai": "^4.1.2",
    "wings-integration": "^1.1.4",
    "zeppelin-solidity": "^1.8.0"
  }
```

**chai to be `dev` dependency**

https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

**Comment by borispovod2** [comment]
yes, sure, but really not so important, devs rare use npm install --prod

**Comment by stefek99** [comment]
> also installed on npm install on a directory that contains package.json, unless you pass the --production flag

True...

I was just worried it takes forever, 40s to install a few `.sol` files!

**Comment by borispovod2** [comment]
It's not installation of sol files man, it's installation of nodejs dependencies.

**Comment by stefek99** [comment]
The reason why anyone is getting this repository is to get a few `.sol` files.

My intention - making process easy, quick, efficient...
